.PHONY: all
all: package

.PHONY: package
package: main.py pla.py Q6.py Q7.py Q8.py requirements.txt README.md
	rm -rf r08922176 r08922176.zip;
	mkdir r08922176;
	cp main.py pla.py Q6.py Q7.py Q8.py requirements.txt README.md r08922176;
	zip -r r08922176.zip r08922176;
